# ==== Game text ====
team_name:
  red: "<bold><red><shadow:#000000a0>RED</shadow></red></bold>"
  gold: "<bold><gold><shadow:#000000a0>ORANGE</shadow></gold></bold>"
  yellow: "<bold><yellow><shadow:#000000a0>YELLOW</shadow></yellow></bold>"
  green: "<bold><green><shadow:#000000a0>GREEN</shadow></green></bold>"
  aqua: "<bold><aqua><shadow:#000000a0>BLUE</shadow></aqua></bold>"
  dark_aqua: "<bold><dark_aqua><shadow:#000000a0>AQUA</shadow></dark_aqua></bold>"
  light_purple: "<bold><light_purple><shadow:#000000a0>PINK</shadow></light_purple></bold>"
  dark_purple: "<bold><dark_purple><shadow:#000000a0>PURPLE</shadow></dark_purple></bold>"

change_team_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>Switch Team"
modify_custom_criteria_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>Edit Custom Criteria"
start_game_item_name: "<italic:false><aqua>[<key:key.use>]<gold>Start Game!"

custom_criteria_name_prefix: "[Custom]"
diamond_behavior_description:
  reduce_others_life: "Remove other teams' life by 1"
  add_self_life: "Add own team's life by 1"

# Preparation Stage
join_spectator_message: "<yellow>You are now <gray><bold>spectator"
join_team_message: "<yellow>You joined team {team_name}"
current_custom_criteria_message: "<yellow>Your team's custom criteria: <white>{name}"
self_set_custom_criteria_message: "<yellow>Set custom criteria to: <white>{name}"
other_set_custom_criteria_message: "<yellow>{player} set custom criteria to: <white>{name}"
not_set_custom_criteria_message: "<yellow>Your team have not set any custom criteria yet"
self_remove_custom_criteria_message: "<yellow>Cleared custom criteria"
other_remove_custom_criteria_message: "<yellow>{player} has cleared custom criteria"
enter_prepare_message: "<yellow>Use the item in hand to <green><bold>select a team</bold><yellow>, then set your team's <green><bold>Custom Criteria"
change_settings_hint_message: "<yellow>Execute <light_purple><hover:show_text:'<aqua>[Click]'><click:run_command:/criteria settings set>/criteria settings set</click></hover><yellow> to modify game settings"
cannot_start_game_message: "<red>Cannot start game from your location, please change your location"

# Game Switch Stage
start_game_message: "<green><bold>GAME START!"
end_game_message:
  announce: "{team_name} <gold> WINS!"
  title: "{team_name}"
  subtitle: "<gold> WINS!"
draw_game_message: "<red>NO ONE WINS"
reset_game_message: "<yellow>Game is reset"

# Trigger Count
trigger_count_message:
  head: "<gray>=====<yellow>Trigger Count<gray>====="
  body: "{player}<white>: <green>{count}"
  tail: "<gray>====================="

# Ingame Stage
ingame_actionbar: "<green>Time before change critera: <red>{time}s<white> || <green>Life count: <red>{life_count}"
criteria_triggered_message:
  announce: "{who_triggered} <gold>has triggered {criteria}"
  title: "{criteria}"
  subtitle: "{who_triggered} <gold>triggered criterion"
auto_change_criteria_message:
  announce: "{team_name} <yellow> has changed criterion, last criterion: {criteria}"
  title: "Criterion Changed"
  subtitle: "<yellow>Last Criterion: {criteria}"
get_diamond_message: "{player} <yellow>gained <aqua>Diamond"
holding_custom_criteria_message: "{team_name} <yellow>has custom criterion [{criteria}<yellow>]"
holding_custom_criteria_click_message: "<dark_aqua><hover:show_text:'<aqua>Click to trigger'>[Click here to trigger]"
guess_hint_message: "<yellow>Type <light_purple><hover:show_text:'<aqua>Click to fill in textbox'><click:suggest_command:/criteria guess>/criteria guess \\<player> \\<guessed or not></click></hover> <yellow> to mark whether player has guessed or not"
guess_cooldown_finished_message: "{team_name} <yellow>can guess criteria now"
guessed_message:
  success:
    announce: "{player} <yellow>guessed correctly, life count <green>+{life_count}<yellow>, last criterion:{criteria}"
    title: "Criterion Changed"
    subtitle: "<yellow>Guess Correctly! Life Count <green>+{life_count}"
  failed:
    announce: "{player} <red>guessed wrongly, life count <dark_red>-{life_count}<red>, last criterion: {criteria}"
    title: "Criterion Changed"
    subtitle: "<red>Guessed Wrongly! Life Count <dark_red>-{life_count}"
eliminated_message:
  announce: "{team_name} <dark_red> was Eliminated"
  title: "{team_name}"
  subtitle: "<dark_red>Eliminated"

# Sidebar
sidebar:
  title: "<shadow:#000000a0><gradient:#ff0000:#EF903E>※ <bold>Don't-do List</bold> ※"
  entry:
    name: "{team_name}<white><shadow:#aa0000a0>[<red><shadow:#aa0000a0>❤<white><shadow:#aa0000a0>{life_count:%02d}]"
    number: "<yellow><shadow:#000000a0>{criteria}"
    number_winner: "<gold><shadow:#000000a0>WINNER"
  entry_dead:
    name: "<strikethrough>{team_name}<gray><shadow:#000000a0>[💔00]"
    number: "<gray><shadow:#000000a0>ELIMINATED"

# custom criterion setting dialog
modify_custom_criteria:
  title: "<aqua><bold>Set Custom criteria"
  body:
    - "<white>Type your custom criteria below."
    - "<white>Click \"Confirm\" to save the changes."
    - "<white>Leave empty to remove your custom criteria"
    - ""
  text_box_title: "<yellow>Content"
  no_button_label: "<white>Cancel"
  yes_button_label: "<white>Confirm"

# /criteria command suggest text
criteria_command:
  failed:
    game_not_start: "Game has not started yet"
    guess_not_enabled: "Guessing rule is disabled"
    invalid_player: "Player %s is eliminated or spectator"
    not_custom_criteria: "Team %s now doesn't hold custom criterion"
    invalid_team_name: "Team %s doesn't exist or already eliminated"
    guess_self_criteria: "Marking yourself as guessed or not is not allowed"
    guess_in_cooldown: "Player %s is in guessing cooldown (Time left: %ds)"
    change_settings_when_not_waiting: "Cannot change game settings when game has started"
  success:
    reset_game: "<yellow>Game has been reset"
    set_life: "<yellow>Set {team_name}'s <yellow>life count to <red>{life_count}"
    get_team_criteria: "{team_name} <yellow>has criterion {criteria}"
    reset_settings: "<yellow>Game settings have been reset"

# 动态配置界面文本
dynamic_settings:
  title: "<aqua><bold>Game Settings"
  yes: "Yes"
  no: "No"
  game_area_size: "<yellow>Game Area Size"
  ingame_difficulty: "<yellow>Minecraft Difficulty in Game"
  life_count: "<yellow>Max Life Count"
  diamond_behavior:
    title: "<yellow>Diamond Behavior"
    add_self_life: "<white>Add self team's life count when gained diamond"
    reduce_others_life: "<white>Reduce other team's life count when gained diamond"
  diamond_behavior_enabled: "<yellow>Diamond Behavior Enabled"
  diamond_behavior_disabled_threshold: "<yellow>In reduce-others-life mode, diamond behavior will be disabled when life count is not above threshold"
  allow_unbalanced_teams: "<yellow>Allow Team Member Count not Balance"
  allow_guess_criteria: "<yellow>Guessing Criteria Rule Enabled"
  guess_success_add_life: "<yellow>Add Life Count when Guessing Correctly"
  guess_failed_reduce_life: "<yellow>Reduce Life Count when Guessing Wrongly"
  save:
    title: "<white>Save Changes"
    start: "<yellow>Saving..."
    success: "<yellow>Game settings saved"
  discard: "<white>Cancel"

# Y-level criteria
y_level_criteria:
  below: "Below %s (Y < %d)"
  above: "Above %s (Y > %d)"
  ground: "Ground"
  on_air: "Height"

# Team selection items
join_team_item:
  red: red_wool
  gold: orange_wool
  yellow: yellow_wool
  green: lime_wool
  aqua: light_blue_wool
  dark_aqua: cyan_wool
  light_purple: pink_wool
  dark_purple: purple_wool
spectator_item: light_gray_wool
modify_custom_criteria_item: writable_book
start_game_item: nether_star

# ==== Ore gen settings ====
# andesite
andesite_generation:
    # depth range, mast be integer. Settings at front are used priorly when ranges overlap.
  - depth: 1..10
    # gen percentage
    ratio: 0.75
# coal ore
coal_ore_generation:
  - depth: 1..3
    ratio: 0.10
  - depth: 4..7
    ratio: 0.07
  - depth: 8..10
    ratio: 0.02
# iron ore
iron_ore_generation:
  - depth: 4..7
    ratio: 0.02
  - depth: 8..10
    ratio: 0.05
# diamond ore
diamond_ore_generation:
  - depth: 8..10
    ratio: 0.01
# bedrock depth
bedrock_depth: 11

# ==== Ingame settings ====
# enable Y-level criteria or not
y_level_criteria_enabled: true
# Y-level criteria height difference from ground, must be integer
y_level_offset:
  ground: 1
  on_air: 14
# auto changed criteria time: seconds
auto_change_criteria_time: 120
