# ==== 游戏文本 ====
team_name:
  red: "<bold><red><shadow:#a0000000>珊瑚红</shadow></red></bold>"
  gold: "<bold><gold><shadow:#a0000000>琥珀金</shadow></gold></bold>"
  yellow: "<bold><yellow><shadow:#a0000000>柠檬黄</shadow></yellow></bold>"
  green: "<bold><green><shadow:#a0000000>翡翠绿</shadow></green></bold>"
  dark_green: "<bold><dark_green><shadow:#a0000000>青柠绿</shadow></dark_green></bold>"
  aqua: "<bold><aqua><shadow:#a0000000>天空蓝</shadow></aqua></bold>"
  blue: "<bold><blue><shadow:#a0000000>深海蓝</shadow></blue></bold>"
  light_purple: "<bold><light_purple><shadow:#a0000000>薰衣粉</shadow></light_purple></bold>"

sidebar:
  title: "<shadow:#a0000000><gradient:#ff0000:#EF903E>※ <bold>禁止事项</bold> ※"
  entry:
    name: "{team_name}<white><shadow:#a0aa0000>[<red>❤</red><white>{life:%02d}]"
    number: "<white><shadow:#a0000000>{criteria}"
  entry_dead:
    name: "<strikethrough>{team_name}<gray><shadow:#a0000000>[💔00]"
    number: "<gray><shadow:#a0000000>已淘汰"

change_team_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>切换队伍"
modify_custom_criteria_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>设置自定义词条"
join_spectator_message: "<yellow>你现在是<gray><bold>旁观者"
join_team_message: "<yellow>你加入了队伍 {team_name}"
current_custom_criteria_message: "<yellow>你的队伍的自定义词条：<white>{name}"
self_set_custom_criteria_message: "<yellow>已将自定义词条设置为：<white>{name}"
other_set_custom_criteria_message: "<yellow>{player}将自定义词条设置为：<white>{name}"
not_set_custom_criteria_message: "<yellow>你的队伍尚未设置自定义词条"
self_remove_custom_criteria_message: "<yellow>已取消自己队伍定义的自定义词条"
other_remove_custom_criteria_message: "<yellow>{player}取消了你的队伍定义的自定义词条"
enter_prepare_message: "<yellow>请使用手上的物品<green><bold>选择队伍</bold><yellow>，然后设置<green><bold>自定义词条"

modify_custom_criteria:
  title: "<aqua><bold>设置自定义词条"
  body:
    - "<white>在下方的文本框修改自定义词条内容"
    - "<white>然后点击“确认”按钮以保存修改"
    - "<white>留空代表取消自己队伍定义的自定义词条"
    - ""
  text_box_title: "<yellow>自定义词条内容"
  no_button_label: "<white>取消"
  yes_button_label: "<white>确认"

criteria_command:
  failed:
    game_not_start: "游戏尚未开始"
    invalid_team_name: "玩家%s已淘汰或者是旁观者"
    guess_self_criteria: "不允许自己标记自己队伍猜中了词条"

# 物品
join_team_item:
  red: red_wool
  gold: orange_wool
  yellow: yellow_wool
  green: lime_wool
  dark_green: green_wool
  aqua: light_blue_wool
  blue: blue_wool
  light_purple: magenta_wool
spectator_item: light_gray_wool
modify_custom_criteria_item: writable_book

# ==== 各方块生成配置 ====
# 安山岩生成
andesite_generation:
  # 深度范围，必须是整数范围。若不同项的范围有重合，则优先使用靠前的项
  - depth: 1..10
    # 生成比例
    ratio: 0.75
# 煤矿石生成
coal_ore_generation:
  - depth: 1..3
    ratio: 0.10
  - depth: 4..7
    ratio: 0.07
  - depth: 8..10
    ratio: 0.02
# 铁矿石生成
iron_ore_generation:
  - depth: 4..7
    ratio: 0.02
  - depth: 8..10
    ratio: 0.05
# 钻石矿石生成
diamond_ore_generation:
  - depth: 8..10
    ratio: 0.01
# 基岩深度
bedrock_depth: 11



# ==== 可在游戏内动态配置的项 ====
# 游戏区域大小
game_area_size: 65
# 最大规则数量（队伍血量）
life_count: 10
# 常规模式下，获取钻石时的行为，可以是reduce_others_life或add_self_life
# reduce_others_life: 减少其他队伍1点生命值
# add_self_life: 增加自己队伍1点生命值
diamond_behavior: reduce_others_life
