# ==== 游戏文本 ====
team_name:
  red: "<bold><red><shadow:#a0000000>红队</shadow></red></bold>"
  gold: "<bold><gold><shadow:#a0000000>橙队</shadow></gold></bold>"
  yellow: "<bold><yellow><shadow:#a0000000>黄队</shadow></yellow></bold>"
  green: "<bold><green><shadow:#a0000000>绿队</shadow></green></bold>"
  aqua: "<bold><aqua><shadow:#a0000000>蓝队</shadow></aqua></bold>"
  dark_aqua: "<bold><dark_aqua><shadow:#a0000000>青队</shadow></dark_aqua></bold>"
  light_purple: "<bold><light_purple><shadow:#a0000000>粉队</shadow></light_purple></bold>"
  dark_purple: "<bold><dark_purple><shadow:#a0000000>紫队</shadow></dark_purple></bold>"

change_team_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>切换队伍"
modify_custom_criteria_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>设置自定义词条"
start_game_item_name: "<italic:false><aqua>[<key:key.use>]<gold>开始游戏！"

custom_criteria_name_prefix: "[自定义]"
diamond_behavior_description:
  reduce_others_life: "减少其他队伍1点生命值"
  add_self_life: "增加自己队伍1点生命值"

# 准备阶段的消息
join_spectator_message: "<yellow>你现在是<gray><bold>旁观者"
join_team_message: "<yellow>你加入了队伍 {team_name}"
current_custom_criteria_message: "<yellow>你的队伍的自定义词条：<white>{name}"
self_set_custom_criteria_message: "<yellow>已将自定义词条设置为：<white>{name}"
other_set_custom_criteria_message: "<yellow>{player}将自定义词条设置为：<white>{name}"
not_set_custom_criteria_message: "<yellow>你的队伍尚未设置自定义词条"
self_remove_custom_criteria_message: "<yellow>已取消自己队伍定义的自定义词条"
other_remove_custom_criteria_message: "<yellow>{player}取消了你的队伍定义的自定义词条"
enter_prepare_message: "<yellow>请使用手上的物品<green><bold>选择队伍</bold><yellow>，然后设置<green><bold>自定义词条"

# 游戏切换阶段的消息
start_game_message: "<green><bold>游戏开始！"
end_game_message:
  announce: "{team_name} <gold>获得胜利"
  title: "{team_name}"
  subtitle: "<gold>获得胜利"
draw_game_message: "<red>无人获胜"
reset_game_message: "<yellow>游戏已重置"

# 触发次数统计
trigger_count_message:
  head: "<gray>=====<yellow>触发次数<gray>====="
  body: "{player}<white>: <green>{count}"
  tail: "<gray>================"

# 游戏进行时的消息
ingame_actionbar: "<green>距离更换词条还有：<red>{time}秒  <green>剩余规则数量：<red>{life_count}"
criteria_triggered_message:
  announce: "{who_triggered} <gold>触发了规则 {criteria}"
  title: "{criteria}"
  subtitle: "{who_triggered} <gold>触发了规则"
auto_change_criteria_message:
  announce: "{team_name} <yellow>更换了词条，上一个词条是：{criteria}"
  title: "词条更换"
  subtitle: "<yellow>上一个词条：{criteria}"
get_diamond_message: "{player} <yellow>获得了 <aqua>钻石"
holding_custom_criteria_message: "{team_name} <yellow>拥有自定义规则 【{criteria}<yellow>】"
holding_custom_criteria_click_message: "<dark_aqua><hover:show_text:'<aqua>点击触发'>【触发规则点这里】"
guess_hint_message: "<yellow>输入<light_purple><hover:show_text:'<aqua>点击填入聊天框'><click:suggest_command:/criteria guess>/criteria guess \\<玩家名\\> \\<是否猜中\\></click></hover> <yellow>来标记玩家是否猜中词条"
guess_cooldown_finished_message: "{team_name} <yellow>现在可以猜词条了"
guessed_message:
  success:
    announce: "{player} <yellow>猜中了词条，剩余规则数<green>+{life_count}<yellow>，上一个词条是：{criteria}"
    title: "词条更换"
    subtitle: "<yellow>猜中词条，剩余规则数<green>+{life_count}"
  failed:
    announce: "{player} <red>猜错了词条，剩余规则数<dark_red>-{life_count}<red>，上一个词条是：{criteria}"
    title: "词条更换"
    subtitle: "<red>猜错词条，剩余规则数<dark_red>-{life_count}"
eliminated_message:
  announce: "{team_name} <dark_red>已淘汰"
  title: "{team_name}"
  subtitle: "<dark_red>已淘汰"

# 侧边栏
sidebar:
  title: "<shadow:#a0000000><gradient:#ff0000:#EF903E>※ <bold>禁止事项</bold> ※"
  entry:
    name: "{team_name}<white><shadow:#a0aa0000>[<red>❤</red><white>{life_count:%02d}]"
    number: "<yellow><shadow:#a0000000>{criteria}"
    number_winner: "<gold><shadow:#a0000000>获胜者"
  entry_dead:
    name: "<strikethrough>{team_name}<gray><shadow:#a0000000>[💔00]"
    number: "<gray><shadow:#a0000000>已淘汰"

# 设置自定义词条界面的文本
modify_custom_criteria:
  title: "<aqua><bold>设置自定义词条"
  body:
    - "<white>在下方的文本框修改自定义词条内容"
    - "<white>然后点击“确认”按钮以保存修改"
    - "<white>留空代表取消自己队伍定义的自定义词条"
    - ""
  text_box_title: "<yellow>自定义词条内容"
  no_button_label: "<white>取消"
  yes_button_label: "<white>确认"

# /criteria命令的文本
criteria_command:
  failed:
    game_not_start: "游戏尚未开始"
    guess_not_enabled: "猜词条玩法未开启"
    invalid_player: "玩家%s已淘汰或者是旁观者"
    not_custom_criteria: "队伍%s当前的词条不是自定义词条"
    invalid_team_name: "队伍%s不存在或已淘汰"
    guess_self_criteria: "不允许自己标记自己猜中了词条"
    guess_in_cooldown: "玩家%s所在队伍正在猜词条冷却中（剩余时间：%d）"

# 物品
join_team_item:
  red: red_wool
  gold: orange_wool
  yellow: yellow_wool
  green: lime_wool
  aqua: light_blue_wool
  dark_aqua: cyan_wool
  light_purple: pink_wool
  dark_purple: purple_wool
spectator_item: light_gray_wool
modify_custom_criteria_item: writable_book
start_game_item: nether_star

# ==== 各方块生成配置 ====
# 安山岩生成
andesite_generation:
  # 深度范围，必须是整数范围。若不同项的范围有重合，则优先使用靠前的项
  - depth: 1..10
    # 生成比例
    ratio: 0.75
# 煤矿石生成
coal_ore_generation:
  - depth: 1..3
    ratio: 0.10
  - depth: 4..7
    ratio: 0.07
  - depth: 8..10
    ratio: 0.02
# 铁矿石生成
iron_ore_generation:
  - depth: 4..7
    ratio: 0.02
  - depth: 8..10
    ratio: 0.05
# 钻石矿石生成
diamond_ore_generation:
  - depth: 8..10
    ratio: 0.01
# 基岩深度
bedrock_depth: 11

# ==== 游戏玩法相关的配置项 ====
# 是否启用有关Y高度的词条
y_level_criteria_enabled: false
# 自动切换词条的时间，必须是整数（单位：秒）
auto_change_criteria_time: 120


# ==== 可在游戏内动态配置的项 ====
# 游戏区域大小
game_area_size: 65
# 最大规则数量（队伍血量）
life_count: 15
# 常规模式下，获取钻石时的行为，可以是reduce_others_life或add_self_life
# reduce_others_life: 减少其他队伍1点生命值
# add_self_life: 增加自己队伍1点生命值
diamond_behavior: reduce_others_life
# 是否启用钻石行为
diamond_behavior_enabled: true
# 钻石行为禁用阈值，当任意一名玩家生命值达到阈值及以下时，钻石行为将禁用
# 此项配置仅在diamond_behavior为reduce_others_life时有效
diamond_behavior_disabled_threshold: 7
# 是否允许各队伍人数不平衡
allow_unbalanced_teams: false
# 是否允许猜词条
allow_guess_criteria: true
# 猜中词条增加的生命值
guess_success_add_life: 1
# 猜错词条减少的规则数
guess_failed_reduce_life: 2
